### ISSUE TITLE
Margin layout attribute not removed when 0

### ISSUE THREAD

**Issue by Fishfield** [ConstraintLayout/constraintlayout.github.io#54]
Actually this is not a bug or anything similar, it is just disturbing at some point to always have attributes like `android:layout_marginTop="0dp"` in case the margin is set to zero in the editor. Is this somehow necessary for some calculations or can you maybe automatically remove the margin attribute when it is 0?

Best,
Thomas

**Comment by danielpassos** [comment]
Hey @Fishfield 

This is something from the editor, it's not required. You can ignore/remove it and the library will understand it's `0dp` (default)

**Comment by Fishfield** [comment]
@danielpassos thank you for the response. 
Ok I got it, nevertheless I'd prefer that the `margins` are not added in the xml files if I select `0dp` in the layout editor. Do you get my point?

**Comment by danielpassos** [comment]
@Fishfield Yes, I got it, but I think there is no option in the editor for this. Not that I know

**Comment by hvisser** [comment]
As mentioned in #63, this is not the issue tracker for constraint layout itself, just for constraintlayout.com please file bugs relating to constraint layout (the library) at https://issuetracker.google.com.
