### ISSUE TITLE
Trivial Guideline Content Update

### ISSUE THREAD

**Issue by fuentespatrick** [ConstraintLayout/constraintlayout.github.io#57]
At the following url:
https://constraintlayout.github.io/basics/guidelines.html

The following paragraph:
"In the current version of Android Studio you will not see the newly created guideline until you click on the blueprint view. If you don’t see it after you create the guideline, just click anywhere inside blueprint view and you’ll see it."

Appears to be outdated. Using the current stable channel version of Android Studio, I'm seeing guidelines appear right away.

I'd submit a PR, but I'm a bit pressed for time today.
Feel free to tag me if you'd prefer I make the time to submit a PR in the next week or two.

**Comment by rock3r** [comment]
This took a lot of time, sorry! But it's now done 8464eb8cb10764ab47084b12762fe0944154553c
