### ISSUE TITLE
Document how to integrate ConstraintLayout

### ISSUE THREAD

**Issue by nateridderman** [ConstraintLayout/constraintlayout.github.io#59]
It would be nice for beginners to see how they can integrate the library in their project, primarily the gradle dependency but also making sure they have the same version of the SDK packages. Putting the current version on the homepage would be nice too.

**Comment by danielpassos** [comment]
Hey, @nateridderman I'm not sure if there is the idea of the contrainlayout website. I think the idea is more cover how it works and that the Google not cover well.

Google has a very good section about how to integrate it into your project. Anyway, I'm not against to have it on the website. 

https://developer.android.com/training/constraint-layout/index.html#add-constraintlayout-to-your-project

**Comment by rock3r** [comment]
@danielpassos is very much right :)

**Comment by rock3r** [comment]
I am going to close this, since it's out of the scope of the website
