### ISSUE TITLE
Margin_left or marign_right is deleted when change positon

### ISSUE THREAD

**Issue by cylee0909** [ConstraintLayout/constraintlayout.github.io#63]
When i set margin_left or margin_right for some subview in xml pannel it works well, but when i try to change position of the widget in the design pannel it's margins will be deleted . When using margin_start or margin_end it works well, but our app's minsdk is 15 , margin_start can't works on it. Hope fix it ๑乛◡乛๑

**Comment by hvisser** [comment]
This is not the right place to report bugs relating to constraint layout, sorry. Please file bugs for constraint layout at: https://issuetracker.google.com/. This issue tracker is only for issues relating to constraintlayout.com which is unaffiliated with Google.
