### ISSUE TITLE
Overlay of Text view over image view article could be shared. 

### ISSUE THREAD

**Issue by Tej333** [ConstraintLayout/constraintlayout.github.io#65]
![screenshot_1518085438](https://user-images.githubusercontent.com/36147802/35967920-61472bde-0ce8-11e8-8af8-651c864e73cc.png)

The image is resized using glide library but my text view is not.

PS:Will not be able to share code.

**Comment by StylingAndroid** [comment]
This is a documentation site, not a tech support forum.

Plus I don';t understand the question, and would not be able to help without the code.
