### ISSUE TITLE
Extra section for examples needed !

### ISSUE THREAD

**Issue by LOG-TAG** [ConstraintLayout/constraintlayout.github.io#67]
We need advanced sample section links! We need samples codes of all advanced demo, tech talks which we are unable to find it ! 
![nicol](https://user-images.githubusercontent.com/1190344/36794062-5265d556-1cc5-11e8-8d48-e718a96b8316.gif)
(None of the code showed on the Demo from Nicol and team is not available anywhere :(  )

**Comment by rock3r** [comment]
Hello there, I am not entirely sure what you would like to see on the website since you're generically referring to "advanced demo". Could you please describe what you're looking for?

**Comment by LOG-TAG** [comment]
@rock3r  I'm looking for the all the source codes of the examples shown by  Nicolas Roard :1st_place_medal:  or similar advanced concepts like replacing collapsible toolbar layout with Toolbar  and using it in Coordinatorlayout with custom ConstraintLayout animation classes! :bulb:

**Comment by rock3r** [comment]
Oh, I see. Well, he's not an author on this website, so we cannot really help you I'm afraid
