### ISSUE TITLE
Typo: Add missing word "for"

### ISSUE THREAD

**Issue by croworc** [ConstraintLayout/constraintlayout.github.io#68]
In file:
&nbsp;&nbsp;https://github.com/ConstraintLayout/constraintlayout.github.io/blob/master/basics/index.md

Change sentence, **from**:
&nbsp;&nbsp;The {{ page.title }} section provides details the basic concepts behind ConstraintLayout and shows how to create things both in XML and the editor. 

**to**:
&nbsp;&nbsp;The {{ page.title }} section provides details **for** the basic concepts...

**Comment by rock3r** [comment]
Thanks, fixed! 8675fb4578192f0b305fdaa80ca7f0a0e62718b5
