### ISSUE TITLE
Typo in a word "preceding" and "weights"

### ISSUE THREAD

**Issue by nirav-tukadiya** [ConstraintLayout/constraintlayout.github.io#81]
https://constraintlayout.com/layouts/linearlayout.html

_preceeding_ - Second line under **Flowed Behaviour in XML**
_wieghts_ - Last line of the page

**Comment by rock3r** [comment]
Thanks for the eagle eye! Fixed :)

**Comment by nirav-tukadiya** [comment]
You're welcome :)

**Comment by StylingAndroid** [comment]
Thanks @nirav-tukadiya and @rock3r
